apiVersion: apps/v1
kind: Deployment
metadata:
  name: tye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tye
  template:
    metadata:
      labels:
        app: tye
    spec:
      containers:
      - image: okteto.dev/tye:latest
        name: tye
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "42caf165-e1d2-42ac-912a-3a9ccd62d266"
        - name: Vless_Path
          value: "/rggdgdwzwe"
        - name: Vmess_UUID
          value: "42caf165-e1d2-42ac-912a-3a9ccd62d266"
        - name: Vmess_Path
          value: "/34resvfge"
        - name: Share_Path
          value: "/v2link"
